title: Michael Winton
url: https://winton.co
description: "Michael Winton's weblog"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll_picture_tag

picture:
  source: "assets/images"
  output: "assets/generated"

# Exclude from processing to `_site`
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - bash
  - bin
  - yarn.lock
  - .envrc
  - mise.toml
  - .github
